In [1]:
import pandas as pd
train = pd.read_csv('train.csv')

In [2]:
train.isnull().sum()

Feature 1     0
Feature 2     0
Feature 3     0
Feature 4     0
Feature 5     0
Feature 6     0
Feature 7     0
Feature 8     0
Feature 9     0
Distance      0
Feature 10    0
Feature 11    0
Feature 12    0
Feature 13    0
Feature 14    0
Class         0
dtype: int64

In [3]:
train.Class.value_counts()

g    8632
h    4682
Name: Class, dtype: int64

In [4]:
train

,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,Distance,Feature 10,Feature 11,Feature 12,Feature 13,Feature 14,Class
0,44.3528,17.3022,2.8228,0.2421,0.1286,-53.7420,13.1133,-9.5446,6.9645,220.4000,X,Y,X,3A0OA29QMU,CYRZQ,g
1,33.5826,11.0346,2.7147,0.4301,0.2459,38.1995,29.6283,6.2741,27.0150,143.9360,T,R,V,99YDVLGRQC,F1X86,h
2,40.9114,11.8167,2.6528,0.4892,0.3062,7.0176,35.4742,5.3901,9.9994,117.8781,S,U,X,RQIVF03R75,00Z0Q,h
3,17.8476,10.4929,2.2742,0.6011,0.3537,20.8677,11.6185,-2.2703,43.7863,65.0150,R,S,U,6W0HC1C64W,PDPTP,g
4,40.6978,30.7397,3.4551,0.1588,0.0805,39.9395,25.9621,8.9297,7.8862,127.0780,Z,R,X,TPTF14C6CK,SNXVE,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13309,100.0190,46.5272,3.1029,0.3377,0.1905,-66.9885,-102.5740,37.0198,26.4890,405.5390,V,Y,V,ISVKBQHPFQ,AXHD7,h
13310,45.3490,28.7095,3.1064,0.3045,0.1969,27.7922,46.6970,-21.9829,6.1306,238.4170,V,S,Y,ACQCIZYNQK,5PUCB,g
13311,47.1071,20.7603,3.1159,0.2098,0.1068,13.5867,32.2989,6.1038,12.8850,178.0970,Y,T,X,EDWHBUHGAK,3XSGC,g
13312,50.4186,16.1182,3.1106,0.2419,0.1260,-31.9187,-30.4202,11.9100,9.6910,126.3790,X,Y,X,EX8KKEHN9R,7C3SF,g
13313,55.0123,11.8425,2.8859,0.3212,0.1606,43.2684,40.8969,-9.7756,50.7270,75.4475,V,R,U,1Q4UDMZD99,DC9W6,h

In [5]:
# 
train['Feature 10'] = train['Feature 10'].astype('category').cat.codes
train['Feature 11'] = train['Feature 11'].astype('category').cat.codes
train['Feature 12'] = train['Feature 12'].astype('category').cat.codes

In [6]:
train

,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,Distance,Feature 10,Feature 11,Feature 12,Feature 13,Feature 14,Class
0,44.3528,17.3022,2.8228,0.2421,0.1286,-53.7420,13.1133,-9.5446,6.9645,220.4000,7,8,4,3A0OA29QMU,CYRZQ,g
1,33.5826,11.0346,2.7147,0.4301,0.2459,38.1995,29.6283,6.2741,27.0150,143.9360,3,1,2,99YDVLGRQC,F1X86,h
2,40.9114,11.8167,2.6528,0.4892,0.3062,7.0176,35.4742,5.3901,9.9994,117.8781,2,4,4,RQIVF03R75,00Z0Q,h
3,17.8476,10.4929,2.2742,0.6011,0.3537,20.8677,11.6185,-2.2703,43.7863,65.0150,1,2,1,6W0HC1C64W,PDPTP,g
4,40.6978,30.7397,3.4551,0.1588,0.0805,39.9395,25.9621,8.9297,7.8862,127.0780,9,1,4,TPTF14C6CK,SNXVE,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13309,100.0190,46.5272,3.1029,0.3377,0.1905,-66.9885,-102.5740,37.0198,26.4890,405.5390,5,8,2,ISVKBQHPFQ,AXHD7,h
13310,45.3490,28.7095,3.1064,0.3045,0.1969,27.7922,46.6970,-21.9829,6.1306,238.4170,5,2,5,ACQCIZYNQK,5PUCB,g
13311,47.1071,20.7603,3.1159,0.2098,0.1068,13.5867,32.2989,6.1038,12.8850,178.0970,8,3,4,EDWHBUHGAK,3XSGC,g
13312,50.4186,16.1182,3.1106,0.2419,0.1260,-31.9187,-30.4202,11.9100,9.6910,126.3790,7,8,4,EX8KKEHN9R,7C3SF,g
13313,55.0123,11.8425,2.8859,0.3212,0.1606,43.2684,40.8969,-9.7756,50.7270,75.4475,5,1,1,1Q4UDMZD99,DC9W6,h

In [7]:
train['Feature 13'].value_counts()

OJI844JANL    1
NA4KWWAJ43    1
YV196QRSNK    1
L7CQ5W8WBT    1
H8YA4D3D2U    1
             ..
6PL4GR87RI    1
V2DE2SO4D3    1
7ZB2XEQD1L    1
ZTII6876AM    1
97IKVEO87E    1
Name: Feature 13, Length: 13314, dtype: int64

In [8]:
# Dropping since it has unique values
train = train.drop('Feature 13', axis=1)

In [9]:
train = train.drop('Feature 14', axis=1)

In [10]:
import pandas as pd
import numpy as np

from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split

In [11]:
X = train.drop('Class',axis=1)
Y = train['Class']
Y

0        g
1        h
2        h
3        g
4        g
        ..
13309    h
13310    g
13311    g
13312    g
13313    h
Name: Class, Length: 13314, dtype: object

In [12]:
xtrain, xtest, ytrain, ytest = train_test_split(X, Y, random_state=42)

In [13]:
train.corr()

,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,Distance,Feature 10,Feature 11,Feature 12
Feature 1,1.000000,0.772866,0.698172,-0.629214,-0.596961,-0.369959,-0.138990,0.018740,-0.005152,0.418659,0.648491,0.204557,0.046165
Feature 2,0.772866,1.000000,0.713052,-0.610338,-0.582067,-0.260817,-0.184259,0.056680,0.067510,0.336096,0.626155,0.161698,-0.035926
Feature 3,0.698172,0.713052,1.000000,-0.851438,-0.809824,-0.153156,0.089882,0.023479,-0.185607,0.434325,0.871090,0.046895,0.251541
Feature 4,-0.629214,-0.610338,-0.851438,1.000000,0.976484,0.108815,-0.115917,-0.013995,0.230424,-0.322688,-0.974602,-0.008495,-0.280849
Feature 5,-0.596961,-0.582067,-0.809824,0.976484,1.000000,0.096864,-0.114710,-0.012273,0.225458,-0.298866,-0.947184,-0.000171,-0.273419
Feature 6,-0.369959,-0.260817,-0.153156,0.108815,0.096864,1.000000,0.279386,-0.019951,-0.059661,-0.215410,-0.116024,-0.824390,0.060226
Feature 7,-0.138990,-0.184259,0.089882,-0.115917,-0.114710,0.279386,1.000000,-0.028360,-0.183809,0.022243,0.127176,-0.350667,0.209134
Feature 8,0.018740,0.056680,0.023479,-0.013995,-0.012273,-0.019951,-0.028360,1.000000,0.013271,0.016445,0.012798,0.015766,-0.012545
Feature 9,-0.005152,0.067510,-0.185607,0.230424,0.225458,-0.059661,-0.183809,0.013271,1.000000,-0.214752,-0.225079,0.084036,-0.935190
Distance,0.418659,0.336096,0.434325,-0.322688,-0.298866,-0.215410,0.022243,0.016445,-0.214752,1.000000,0.339806,0.178081,0.265562
Feature 10,0.648491,0.626155,0.871090,-0.974602,-0.947184,-0.116024,0.127176,0.012798,-0.225079,0.339806,1.000000,0.013255,0.280676
Feature 11,0.204557,0.161698,0.046895,-0.008495,-0.000171,-0.824390,-0.350667,0.015766,0.084036,0.178081,0.013255,1.000000,-0.080357
Feature 12,0.046165,-0.035926,0.251541,-0.280849,-0.273419,0.060226,0.209134,-0.012545,-0.935190,0.265562,0.280676,-0.080357,1.000000

In [14]:
# import seaborn as sns
# sns.pairplot(data=train)

In [15]:
train.describe

<bound method NDFrame.describe of        Feature 1  Feature 2  Feature 3  Feature 4  Feature 5  Feature 6  \
0        44.3528    17.3022     2.8228     0.2421     0.1286   -53.7420
1        33.5826    11.0346     2.7147     0.4301     0.2459    38.1995
2        40.9114    11.8167     2.6528     0.4892     0.3062     7.0176
3        17.8476    10.4929     2.2742     0.6011     0.3537    20.8677
4        40.6978    30.7397     3.4551     0.1588     0.0805    39.9395
...          ...        ...        ...        ...        ...        ...
13309   100.0190    46.5272     3.1029     0.3377     0.1905   -66.9885
13310    45.3490    28.7095     3.1064     0.3045     0.1969    27.7922
13311    47.1071    20.7603     3.1159     0.2098     0.1068    13.5867
13312    50.4186    16.1182     3.1106     0.2419     0.1260   -31.9187
13313    55.0123    11.8425     2.8859     0.3212     0.1606    43.2684

       Feature 7  Feature 8  Feature 9  Distance  Feature 10  Feature 11  \
0        13.1133    -9.5446     6.9645  220.4000           7           8
1        29.6283     6.2741    27.0150  143.9360           3           1
2        35.4742     5.3901     9.9994  117.8781           2           4
3        11.6185    -2.2703    43.7863   65.0150           1           2
4        25.9621     8.9297     7.8862  127.0780           9           1
...          ...        ...        ...       ...         ...         ...
13309  -102.5740    37.0198    26.4890  405.5390           5           8
13310    46.6970   -21.9829     6.1306  238.4170           5           2
13311    32.2989     6.1038    12.8850  178.0970           8           3
13312   -30.4202    11.9100     9.6910  126.3790           7           8
13313    40.8969    -9.7756    50.7270   75.4475           5           1

       Feature 12 Class
0               4     g
1               2     h
2               4     h
3               1     g
4               4     g
...           ...   ...
13309           2     h
13310           5     g
13311           4     g
13312           4     g
13313           1     h

[13314 rows x 14 columns]>

In [16]:
from sklearn import preprocessing

In [17]:
normal_X = preprocessing.scale(xtrain)
normal_Xtest = preprocessing.scale(xtest)

In [18]:
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score

In [55]:
lgbm = LGBMClassifier(objective='binary', random_state=5)

lgbm.fit(normal_X, ytrain)

y_pred = lgbm.predict(normal_Xtest)

In [56]:
y_pred

array(['g', 'g', 'g', ..., 'g', 'h', 'h'], dtype=object)

In [57]:
accuracy_score(ytest, y_pred)

0.8891559026734756

In [29]:
test = pd.read_csv('test.csv').drop('ID',axis=1)

In [31]:
# Dropping since it has unique values
test = test.drop('Feature 13', axis=1)

In [32]:
test = test.drop('Feature 14', axis=1)

In [36]:
test['Feature 10'] = test['Feature 10'].astype('category').cat.codes
test['Feature 11'] = test['Feature 11'].astype('category').cat.codes
test['Feature 12'] = test['Feature 12'].astype('category').cat.codes

In [62]:
test = preprocessing.scale(test)

In [63]:
test

array([[ 0.76468602, -0.25481462,  0.67439191, ...,  1.22665547,
         1.561774  , -0.985121  ],
       [-0.45680764, -0.20535112,  0.50680099, ...,  0.52951442,
        -1.2339852 ,  0.52120336],
       [-0.88835915, -0.56164636, -1.15793551, ..., -1.2133382 ,
         0.1638944 ,  0.01909524],
       ...,
       [-0.80602532, -0.65962299, -1.07424545, ..., -0.86476767,
        -0.8845153 , -1.48722912],
       [-0.69218891, -0.22936457, -0.6914214 , ..., -0.16762662,
        -0.1855755 , -1.48722912],
       [-0.33638453,  0.13701455,  0.11470147, ...,  0.52951442,
         0.1638944 ,  0.52120336]])

In [64]:
prediction = lgbm.predict(test)

In [70]:
prediction

array(['h', 'g', 'g', ..., 'g', 'g', 'g'], dtype=object)

In [66]:
tt = pd.read_csv('test.csv')

In [67]:
sample_submission = pd.DataFrame({'ID': tt['ID'].values, 'Class': prediction})

sample_submission['Class'] =  prediction
sample_submission = sample_submission.replace('1', 'h')
sample_submission = sample_submission.replace('0', 'g')

In [68]:
sample_submission

         ID Class
0     13154     h
1      2571     g
2      1320     g
3     16907     h
4      5570     g
...     ...   ...
5701  16632     h
5702  11032     g
5703  15068     g
5704  10456     g
5705    958     g

[5706 rows x 2 columns]

In [69]:
sample_submission.to_csv('Submission.csv', index=False)